<?php

namespace ContainerBwcFlM5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YyLDgIVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yyLDgIV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yyLDgIV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'location' => ['privates', '.errored..service_locator.yyLDgIV.App\\Entity\\Location', NULL, 'Cannot autowire service ".service_locator.yyLDgIV": it needs an instance of "App\\Entity\\Location" but this type has been excluded in "config/services.yaml".'],
            'util' => ['privates', 'App\\Service\\WeatherUtil', 'getWeatherUtilService', true],
        ], [
            'location' => 'App\\Entity\\Location',
            'util' => 'App\\Service\\WeatherUtil',
        ]);
    }
}
