<?php

namespace ContainerBwcFlM5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountryCodeCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CountryCodeCommand' shared autowired service.
     *
     * @return \App\Command\CountryCodeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CountryCodeCommand.php';

        $container->privates['App\\Command\\CountryCodeCommand'] = $instance = new \App\Command\CountryCodeCommand(($container->privates['App\\Repository\\LocationRepository'] ?? $container->load('getLocationRepositoryService')), ($container->privates['App\\Service\\WeatherUtil'] ?? $container->load('getWeatherUtilService')));

        $instance->setName('weather:city');
        $instance->setDescription('Displays measurements for city in country');

        return $instance;
    }
}
