<?php

namespace ContainerAdR7T1O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocation3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yyLDgIV.App\Entity\Location' shared service.
     *
     * @return \App\Entity\Location
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.yyLDgIV": it needs an instance of "App\\Entity\\Location" but this type has been excluded in "config/services.yaml".');
    }
}
